name: repository_dispatch.yaml

on:
  repository_dispatch:
    types: [ repository_dispatch ]
    inputs:
      title:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: echo
      run: |
        echo "title: ${{ github.event.client_payload.title }}"
