name: comment test

on: issue_comment

jobs:
  comment-test:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/preview')
    steps:
      - run: echo ${{ join(github.event.issue.labels.*.name, ' ') }}
      - run: echo ${{ join(github.event.issue.labels.*.name, ',') }}

  label-test-1:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/preview') &&
      contains(github.event.issue.labels.*.name, 'preview:shared')
    steps:
      - run: echo ${{ join(github.event.issue.labels.*.name, ' ') }}
      - run: echo ${{ join(github.event.issue.labels.*.name, ',') }}

  label-test-2:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/preview') &&
      contains(github.event.issue.labels.*.name, 'preview:pr')
    steps:
      - run: echo ${{ join(github.event.issue.labels.*.name, ' ') }}
      - run: echo ${{ join(github.event.issue.labels.*.name, ',') }}

