name: workflow_run.yml

on:
  workflow_run:
    workflows:
      - "test.yaml"

jobs:
  dump:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Dump GitHub context
      id: github_context_step
      continue-on-error: true
      run: echo '${{ toJSON(github) }}'
    - name: test
      run: |
        PR_NUMBER=${{ join(github.event.workflow_run.pull_requests.*.number, '') }}
        BASE_BRANCH="${{ join(github.event.workflow_run.pull_requests.*.base.ref, '') }}"
        
        echo "PR #$PR_NUMBER targeting $BASE_BRANCH"
